sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
before_script:
  - npm prune
  - cd test/one; npm run install-hub
  - cd test/one; npm run npm run start-hub &
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
