sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
before_script:
  - npm prune
  - cd test/one; npm install; npm run install-hub
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm run start-hub &
  - cd ../..
script:
  - npm test
  # - cd test/one; npm run test-in-parallel
  - cd test/one
  - npm test # run sequence
  - cd ../..
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
