sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
before_script:
  - npm prune
  - cd test/one; npm install; npm run install-hub
  - cd test/one; npm run start-hub &
script:
  - npm test
  - cd test/one; npm run test-in-parallel
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
